print("Hisssssss...")
print("Hello, World!")
print("\nHello, World!")
print("The itsy bitsy spider\nclimbed up the waterspout.")
print()
print("Down came the rain\nand washed the spider out.")
print("\\")
print("My name is ", end="")
print("Monty Python.")
