"""ExercíciosConceitosBásicosdePython
1.FaçaumProgramaquepeçadoisnúmeros,realizeasprincipaisoperaçõessoma,subtração,multiplicação,divisão
2.Peçaaousuárioparainformaroanodenascimento.Emseguida,calculeeimprimaaidadeatual.
3.FaçaumProgramaquepeçaaquantidadedequilômetros,transformeemmetros,centímetrosemilímetros.
4.Recebadousuárioaquantidadedelitrosdecombustívelconsumidoseadistânciapercorrida.Calculeeimprimaoconsumomédioemkm/l.
5.Escrevaumprogramaquecalculeotempodeumaviagem.Façaumcomparativodomesmopercursodeavião,carroeônibus.Levandoemconsideração:●avião=600km/h●carro=100km/h●ônibus=80km/h
6.Soliciteaousuárioopesoemkgeaalturaemmetros.CalculeeimprimaoÍndicedeMassaCorporal(IMC)usandoafórmula:IMC=peso/(alturaxaltura).
7.FaçaumProgramaqueperguntequantovocêganhaporhoraeonúmerodehorastrabalhadasnomês.Calculeemostreototaldoseusalárionoreferidomês.
8.Soliciteaousuárioonúmerodehorasdeexercíciofísicoporsemana.Calculeototaldecaloriasqueimadasemummês,considerandoumamédiade5caloriasporminutodeexercício.
9.Faça um Programa que utilize 4variáveis como preferir e no final print uma mensagem amigável utilizando as variáveis criadas.
Exemplosdevariáveis:nome,idade,lugar,profissão....
Exemploderetorno:OláMaria,prazerteconhecer.SoudeSãoPaulotambémeestoumigrandodeárea.Lembrandoqueparaoretornovamosusarprintcomasvariáveiscriadaseestetextoésomenteumexemplo,utilizemacriatividade
"""
